Color themes and migrations

diff --git a/bin/setup b/bin/setup
--- a/bin/setup
+++ b/bin/setup
@@ -1,8 +1,23 @@
 #!/usr/bin/env bash
 set -euo pipefail
 IFS=$'\n\t'
+# set -vx
+
+# This makes sure all of the scripts we need to load are loaded from
+# the executing script folder so they can be found
+DIR="$( cd "$( dirname $0 )" >/dev/null 2>&1 && pwd )"
+pushd $DIR >/dev/null 2>&1
+ruby ./migrate.rb
+popd >/dev/null 2>&1
+
+# . migrate.rb
+exit_code=$?
+if [ $exit_code -ne 0 ]; then
+  echo '$exit_code was not 0 (error/exit)'
+  exit $exit_code
+fi
+
+echo '$exit_code was 0 (success)'
+
 set -vx
-
 bundle install
-
-# Do any other automated setup that you need to do here
